config/routes.rb
Project1::Application.routes.draw do




  resources :contract_relationships

  resources :contracts

  resources :contract_subject_roles

  resources :contract_subject_selects

  resources :contract_subjects


  resources :contract_types


  resources :contractor_representatives


  resources :unv_comments


  resources :truck_drivers


  resources :couplers


  resources :unv_employees


  resources :resourse_types


  resources :unv_types


  resources :employee_histories


  resources :employees
  post "employees/index"

  resources :staff_units


  resources :departments do

  end


  get "unavailables/index"
  get "unavailables/ol"
  get "unavailables/upd"
  get "unavailables/connections"


  resources :duties


  get "wialon/index"

  resources :tables


  resources :columns


  resources :objecttypepropertycolumns


  resources :objecttypeproperties


  resources :objecttypes


  resources :systems


  resources :phoneuses


  resources :phones


  resources :positions


  resources :contractortypes


  resources :contractors


  resources :documents do
       collection do
         get 'show_part'
         post 'select_kind'
         get 'select_kind'
         get 'edit'
       end
  end


  resources :documentkinds


  resources :documenttypes


  resources :functionalgroups do
       collection do
         get 'set_order'
         post 'savesort'
         get 'savesort'
         get 'update_menu'
       end
  end


  resources :people do
     collection do
      get 'phone_person'
     end
  end


  resources :transportexploitations


  resources :transporttanks


  resources :transportloadings


  resources :transportecologicals


  resources :enginemodels


  resources :enginetypes


  resources :transportkinds


  resources :transportcolors


  resources :transporttypes


  resources :transports



  get "sms/index"

  resources :testguids, as: 'tst'




  devise_for :admins







  get "main/index"









   root :to => 'main#index'
   match '/' => 'main#index'
   
   

devise_for :users, :skip => [:sessions]
as :user do
  get 'signin' => 'devise/sessions#new', :as => :new_user_session
  post 'signin' => 'devise/sessions#create', :as => :user_session
  delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
end

scope "/admin" do
  resources :users, :usergroups, :roles, :functionals
end

scope "/transport" do
  resources :transportbrands
  resources :transportmodels
  resources  :transportcategories
end


match ':controller(/:action(/:id))(.:format)'
  
end

app/models/transport.rb
# -*- encoding : utf-8 -*-
class Transport < ActiveRecord::Base
  attr_accessible :description, :name, :vin, :body_num, :chassis_num, :engine_num, :year, :weight, :capacity, :reg_num, :is_close,
                  :overall_height, :overall_width, :overall_length, :useful_height, :useful_width, :useful_length, :useful_volume,
                  :registration_date, :deregistration_date

  

  validates :reg_num, :vin,  presence: true
  validates :year,  presence: true,
                    numericality: true,
                    length: {minimum: 1, maximum: 4}
  validates :reg_num, :vin, uniqueness: true, on: :update


  has_many :tsloadings
  has_many :tstanks

  has_one :truck, :class_name => 'Coupler', :foreign_key => 'truck_id'
  has_one :trailer, :class_name => 'Coupler', :foreign_key => 'trailer_id'
  has_many :truck_drivers


  has_and_belongs_to_many :transportbrands
  has_and_belongs_to_many :transportmodels
  has_and_belongs_to_many :transportcategories
  has_and_belongs_to_many :transportcolors
  has_and_belongs_to_many :transportexploitations
  has_and_belongs_to_many :enginemodels

  has_and_belongs_to_many :documents
  
  audited

  before_validation :ensure_uuid


  def truck
    Coupler.where({truck_id: self.id, is_close: false}).first
  end

  def trailer
    Coupler.where({trailer_id: self.id, is_close: false}).first
  end


  def used_truck?
    self.truck && !self.truck.is_close
  end

  def used_trailer?
    self.trailer && !self.trailer.is_close
  end


  scope :visible, where("transports.is_close != ?", true)
  scope :trucks, visible.joins(transportmodels: [ transportkinds: :transporttype ] ).where("[transporttypes].id = ?", 'eee53245-a100-42d3-8b36-c4b891dca119')
  scope :trailers, visible.joins(transportmodels: [ transportkinds: :transporttype ] )
            .where("[transporttypes].id = ? or [transporttypes].id = ? or [transporttypes].id = ? or [transporttypes].id = ? ",
              '1e475762-b77b-427b-99de-e9350b455b13' , 'f8902d5a-762b-4188-b698-b893fbc0553c', '1d7b592f-8d12-4c4d-bc5a-71484efc1fff', '2c505e83-7074-46b1-ad55-5254a7067476')
  scope :used_trucks, lambda { trucks.map { |t| t if t.used_truck? }.compact }
  scope :used_trailers, lambda { trailers.map { |t| t if t.used_trailer? }.compact }
  scope :free_trucks, lambda { trucks - used_trucks }
  scope :free_trailers, lambda { trailers - used_trailers }






  def document
     self.documents.any? ? self.documents.first : false
  end

  def close
    self.update_attribute( :is_close, true )
  end

  def unclose
    self.update_attribute( :is_close, false )
  end

  def transportmodel
    self.transportmodels.any? ? self.transportmodels.first : false
  end

  def transportexploitation
    self.transportexploitations.any? ? self.transportexploitations.first : false
  end

  def transporttype
    self.transportmodel && self.transportmodel.transportkinds.first.any?  && self.transportmodel.transportkinds.first.transporttype ? self.transportmodel.transportkinds.first.transporttype : false
  end


  def enginemodel
    self.enginemodels.any? ? self.enginemodels.first : false
  end


  def transportcolor
    self.transportcolors.any? ? self.transportcolors.first : false
  end


 def ensure_uuid
    self.id ||= SecureRandom.uuid
 end



end

app/models/transporttype.rb
# -*- encoding : utf-8 -*-
class Transporttype < ActiveRecord::Base
  attr_accessible :name, :transportcategory_id , :descr, :is_close

  audited

  belongs_to :transportcategory
  has_many :transportkinds

  validates :name, presence: true

  scope :visible, where("is_close != ?", true)

  def close
    self.update_attribute( :is_close, true )
  end

  def unclose
    self.update_attribute( :is_close, false )
  end


end

app/controllers/transports_controller.rb
# -*- encoding : utf-8 -*-
class TransportsController < ApplicationController

  def index
    if params[:showdel] == "true"
      @transports = Transport.order('reg_num desc').paginate(page: params[:page], per_page: 30)
    else
      @transports = Transport.visible.order('reg_num desc').paginate(page: params[:page], per_page: 30)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transports }
    end
  end



  def new
    @transport = Transport.new

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @transport }
    end
  end


  def edit
    @transport = Transport.find(params[:id])
    
    if params[:copy]
      @copy = Marshal.load(Marshal.dump(@transport.attributes))
      @copy.delete('id')
      @copy.delete('created_at')
      @copy.delete('updated_at')
      @transport_copy = Transport.create(@copy)
      @transport_copy.transportmodels << @transport.transportmodel if @transport.transportmodel
      @transport_copy.transportexploitations << @transport.transportexploitation if @transport.transportexploitation
      @transport_copy.enginemodels << @transport.enginemodel if @transport.enginemodel
      @transport_copy.transportcolors << @transport.transportcolor if @transport.transportcolor
      @transport = @transport_copy
    end
    transport_stats(@transport)
    
    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @transport }
    end
  end


  def create
    @transport = Transport.new(params[:transport])

    respond_to do |format|
      if @transport.save
        format.html { redirect_to edit_transport_path(@transport), notice: 'ТС сохранено.' }
      # format.json { render json: @transport, status: :created, location: @transport }
      else
       # format.js   {}
        transport_stats(@transport)
        flash[:notice] = "Error"
        format.html { render action: "new" }
       # format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
      #render action: "update"
    end
  end


  def update
    @transport = Transport.find(params[:id])
    
    respond_to do |format|
      if @transport.update_attributes(params[:transport])
         transport_stats(@transport)
         flash[:notice] = "Ok"
         format.html { redirect_to edit_transport_url(@transport), notice: 'ТС сохранено.' }
#        format.json { head :no_content }
      else
        format.js   {}
        transport_stats(@transport)
         flash[:notice] = "Error"
        format.html { render action: "edit" }
#        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @transport = Transport.find(params[:id])
    current_user.admin ? @transport.destroy : @transport.close

    respond_to do |format|
      format.html { redirect_to transports_url }
      format.json { head :no_content }
    end
  end

  def remove_doc
    @document = Document.find(params[:id])
    tmp = @document
    tmp_tr = tmp.transport
    current_user.admin ? @document.destroy : @document.close

    respond_to do |format|
      format.html { redirect_to transports_url, notice: "Документ #{tmp.documentkind.name} для #{tmp_tr.reg_num} удален" }
      format.json { head :no_content }
    end
  end




  def transport_stats(transport)
    @transportmodel = transport.transportmodel if transport.transportmodel #модель ТС
    if @transportmodel
      @transportmodel_name = @transportmodel.name
      @transportbrand = @transportmodel.transportbrand.name # марка ТС
      @transportengine = @transportmodel.enginetypes.first if @transportmodel.is_engine #наличие двигателя
      @transportloadings = (transport.tsloadings.any? ? transport.tsloadings : @transportmodel.transportloadings) if @transportmodel.is_loading #наличие погрузки
      @transportfuellings = (transport.tstanks.any? ? transport.tstanks : @transportmodel.transporttanks) if @transportmodel.is_fuelling #наличие топл. бака
      @transportkind = @transportmodel.transportkinds.first.name if @transportmodel.transportkinds.any? #Вид ТС
      @transporttype = @transportmodel.transportkinds.first.transporttype.name if @transportkind # Тип ТС
      @transportcategory = @transportmodel.transportkind.transporttype.transportcategory.name if @transporttype # Категория ТС
      @enginetype = @transportmodel.enginetypes.first.name if @transportmodel.enginetypes.any?
    end
    @transportexploitation = transport.transportexploitation.name if transport.transportexploitation
    @enginemodel = transport.enginemodel if transport.enginemodel #модель двигателя
    if @enginemodel
      @enginemodel_name = @enginemodel.name
      @enginemodel_power = @enginemodel.power
      @enginemodel_power_kvt = @enginemodel.power_kvt
      @enginemodel_displacement = @enginemodel.displacement
    end
    @transportcolor = transport.transportcolor.name if transport.transportcolor #цвет тс
  end




  def select_brand
   respond_to do |format|
      format.js   {}
   end
     @transport = Transport.find(params[:id])
     
#    @transportbrand = Transportbrand.find(params[:brand][:id])
#    @transport.transportbrands.delete( @transport.transportbrands )
#    @transport.transportmodels.delete( @transport.transportmodels )
#    @transport.transportbrands << @transportbrand

    @transportmodel = Transportmodel.find(params[:model])
    @transport.transportmodels.delete( @transport.transportmodels )
    @transport.transportmodels << @transportmodel
    transport_stats(@transport)

    flash[:notice] = 'Модель ТС сохранена.'
    render action: "complete"

  end



  def select_category
   respond_to do |format|
      format.js   {}
   end
    @transport = Transport.find(params[:id])
    @transportcategory = Transportcategory.find(params[:category][:id])
    @transport.transportcategories.delete( @transport.transportcategories )
    @transport.transportcategories << @transportcategory
    @div = "select_category#{@transport.id}"
    flash[:notice] = 'Категория сохранена'

  end


  def select_color
   respond_to do |format|
      format.js   {}
   end
    @transport = Transport.find(params[:id])

    @transportcolor = Transportcolor.find(params[:color][:id])
    @transport.transportcolors.delete( @transport.transportcolors )
    @transport.transportcolors << @transportcolor
    @div = "popup_content"
    transport_stats(@transport)
    flash[:notice] = 'Цвет ТС выбран'
    render action: "complete"
  end


  def select_exploitation
   respond_to do |format|
      format.js   {}
   end
    @transport = Transport.find(params[:id])
    
    @exploitation = Transportexploitation.find(params[:exploitation][:id])
    @transport.transportexploitations.delete( @transport.transportexploitations )
    @transport.transportexploitations << @exploitation
    @div = "popup_content"
    transport_stats(@transport)
    flash[:notice] = 'Форма эксплуатации ТС выбрана'
    render action: "complete"
  end

  def select_enginemodel
   respond_to do |format|
      format.js   {}
   end
    @transport = Transport.find(params[:id])
    @enginemodel = Enginemodel.find(params[:enginemodel][:id])

    @transport.enginemodels.delete( @transport.enginemodels )
    @transport.enginemodels << @enginemodel
    transport_stats(@transport)
    flash[:notice] = "сохранена модель двигателя: #{@enginemodel.name}"
    render action: "complete"
  end

  def select_loading
    respond_to do |format|
      format.js   {}
    end
    @transport = Transport.find(params[:id])
    @transport.tsloadings.create(loading: params[:tsloading][:loading])
    @transport.reload
    transport_stats(@transport)
    flash[:notice] = 'Тип загрузки добавлен'
    render action: "complete"
  end

  def del_loading_from_transport
    @transport = Transport.find(params[:id])
    Tsloading.find(params[:loading]).delete
    transport_stats(@transport)
    flash[:notice] = 'Тип загрузки удален'
    render action: "complete"
  end

  def select_tank
    respond_to do |format|
      format.js   {}
    end
    @transport = Transport.find(params[:id])
    @transport.tstanks.create( v_tank: params[:tstank][:v_tank], v_tank_min: params[:tstank][:v_tank_min] )
    @transport.reload
    transport_stats(@transport)
    flash[:notice] = 'Топливный бак добавлен'
    render action: "complete"
  end

  def del_tank_from_transport
    @transport = Transport.find(params[:id])
    Tstank.find(params[:tank]).delete
    transport_stats(@transport)
    flash[:notice] = 'Топливный бак удален'
    render action: "complete"
  end



  def show_part
   respond_to do |format|
      format.js   {}
   end
   @part = params[:part]
   @transport = Transport.find(params[:id]) if params[:id]
  end


  def complete

  end

end

app/helpers/transports_helper.rb
# -*- encoding : utf-8 -*-
module TransportsHelper
end

app/views/transports/_additional.erb
<table>
  <tr>
    <th>Марка ТС</th> <td><%= @transportbrand %></td>
    <th>Модель ТС</th> <td><%= @transportmodel_name %></td>
    <th style="width: 22%;">
      <%= link_to action: "show_part", part: "transport_brand", id: @transport , remote: true do %>
      <%= image_tag( "edit.png", style: "width: 20px; cursor: pointer;") %> Редактировать.
      <% end %>
    </th>
  </tr>

</table>

<table>
  <tr>  
    <th>Категория ТС</th>
    <th>Тип ТС</th>
    <th>Вид ТС</th>
  </tr>
  <tr>
    <td><div id="transportcategory"><%= @transportcategory %></div></td>
    <td><div id="transporttype"><%= @transporttype %></div></td>
    <td><div id="transportkind"><%= @transportkind %></div></td>
  </tr>
</table>

<table style="table-layout:fixed;">
  <tr>
    <th>Тип двигателя </th>
    <th>Способ погрузки
          <%= link_to action: "show_part", part: "select_loading", id: @transport , remote: true do %>
            <%= image_tag( "edit.png", style: "width: 20px; cursor: pointer;") %> Редактировать.
          <% end if @transportloadings%>
    </th>
    <th>Топливный бак
           <%= link_to action: "show_part", part: "select_tank", id: @transport , remote: true do %>
            <%= image_tag( "edit.png", style: "width: 20px; cursor: pointer;") %> Редактировать.
          <% end if @transportfuellings%>
    </th>
  </tr>
  <tr>
    <td><%= @transportengine ? @enginetype : "нет" %> </td>
    <td>
      <% if @transportloadings %>
        <% for l in @transportloadings %>
          [<%= l.loading%>]
        <% end %>
      <% else %>
          нет
      <% end %>
    </td>
    <td>
      <% if @transportfuellings %>
        <% @transportfuellings.each do |tank|  %>
          <b>Объём бака:</b> <%= tank.v_tank %>; <b>Мин. остаток:</b> <%= tank.v_tank_min %>, <br/>
        <% end %>
      <% else %>
          нет
      <% end %>
    </td>
  </tr>
  
</table>


<table>
  <tr>  
     <th>Цвет
          <%= link_to action: "show_part", part: "transport_color", id: @transport , remote: true do %>
          <%= image_tag( "edit.png", style: "width: 20px; cursor: pointer;") %> Редактировать.
          <% end %>
     </th>
     <td><%= @transportcolor %></td>
     <th>Форма эксплуатации
          <%= link_to action: "show_part", part: "transport_exploitation", id: @transport , remote: true do %>
          <%= image_tag( "edit.png", style: "width: 20px; cursor: pointer;") %> Редактировать.
          <% end %>
     </th>
     <td><%= @transportexploitation %></td>
  </tr>
</table>

<table>
  <tr>  <th>Модель двигателя</th> <th>Мощность двигателя л.с.</th> <th>Мощность двигателя кВт</th> <th>Рабочий объём двигателя</th> </tr>
  <tr>  <td> <%= @enginemodel_name%>  </td> <td><%= @enginemodel_power%>  </td> <td><%= @enginemodel_power_kvt%>  </td> <td><%= @enginemodel_displacement%>  </td>  </tr>
  <tr>  <th colspan="3">
          <%= link_to action: "show_part", part: "transport_engine", id: @transport , remote: true do %>
          <%= image_tag( "edit.png", style: "width: 20px; cursor: pointer;") %> Редактировать.
          <% end %>
        </th>
  </tr>

</table>

app/views/transports/_docs.erb
<table>
  <tr>
    <th> Документы:</th><td colspan="2"><%= link_to "Создать документ", action: "show_part", part: "select_new_document", id: @transport,  remote: true %> </td>
  </tr>
  <% @transport.documents.visible.each do |document| %>
  <tr>
    <th><%=  document.documentkind.name if document.documentkind %></th> 
    <td class="edit" title="Редактировать"><%= link_to image_tag("edit.png"),edit_document_path(document) %></td>
    <td class="del" title="Удалить"><%= link_to image_tag("remove.png"), action: :remove_doc, id: document, method: :delete, data: { confirm: 'Точно?' } %></td>
  </tr>
   <% end if @transport.documents.any? %>
</table>

app/views/transports/_select_loading.erb
<% if transport.tsloadings.any? %>
<table>
  <tr> <th> Удалить тип погрузки</th>
    <td>
      <% for loading in transport.tsloadings do %>
      <span style="margin-right: 5px; display: block;">
       [<%=  loading.loading %>
        <%= link_to 'x', url_for(action: "del_loading_from_transport", id: transport , loading: loading ) , remote: true , style: "color: red; font-weight: bold;", data: { confirm: 'Точно?' } %>]
      </span>
      <% end %>
    </td>
  </tr>
</table>
<% end %>


<%= form_tag  url_for( action: 'select_loading' , id: transport ) , remote: true do %>
<table style="width: 100%;">
  <tr>
    <th>Тип погрузки</th>
    <th></th>
  </tr>
  <tr>
    <td>
      <%= text_field :tsloading, :loading , autofocus: true %>
    </td>
    <th>
      <%= submit_tag "Сохранить" , id: "transporttank" %>
    </th>
  </tr>
</table>
<% end %>

app/views/transports/_select_new_document.erb
<% @documnetkinds = Documentkind.for_transport %>

<%= form_tag new_document_path(transport: transport) do %>
<table>
  <tr>
    <th> Вид документа ТС</th>
    <td> <%= collection_select( :documentkind, :id, @documnetkinds, :id, :name ) %>
    </td>
    <th>
       <%= submit_tag "Создать" %>
    </th>
  </tr>

</table>
<% end %>

app/views/transports/_transport_brand.erb
<% @brands = Transportbrand.visible.sort_by(&:name)
@models = Transportmodel.all.sort_by(&:transportbrand_id)
%>


<%= form_tag  url_for( action: 'select_brand', id: transport) , remote: true do %>
<table style="width: 100%">
  <tr>
    <th><%= label :brand , "Марка ТС" %> </th>
        <td>
<%= collection_select( :brand, :id, @brands, :id, :name,  { prompt: "Выберите марку ТС"}  ) %>
    </td>
  </tr>
    <tr>
    <th><%= label :model , "Модель ТС" %> </th>
        <td>
<%= select_tag(:model,  options_for_select(@models.map { |m| [m.name, m.id, { class: m.transportbrand_id}] }), { prompt: "Выберите модель ТС" }) %>
    </td>
  </tr>

  <tr> <th colspan="2"> <%= submit_tag "Сохранить", id: "model_submit", style: "display: none;"  %>  </th> </tr>
</table>

<% end %>


<script>
  $(function() {

    /* For jquery.chained.js */
    $("#model").chained("#brand_id");


    /* Show button after each pulldown has a value. */
    $("#model").bind("change", function(event) {
        if ("" != $("option:selected", this).val() && "" != $("option:selected", $("#brand_id")).val() )
        {
            $("#model_submit").fadeIn();
        } else {
            $("#model_submit").hide();
        }
    });
  });
</script>

app/views/transports/_transport_category.erb
<% @categories = Transportcategory.all %>

<div id="select_category<%=transport_category.id%>">

<%= form_tag  url_for( action: 'select_category' , id: transport_category ) , remote: true do %>

<%= collection_select( :category, :id, @categories, :id, :name ,
  { prompt: transport_category.transportcategories.blank? ? "Выберите категорию" : nil,
    selected: transport_category.transportcategories.any? ? transport_category.transportcategories.first.id.to_s : nil} ,
    onchange: "$(this.form).submit();" ) %>


<% end %>


<%#= form_tag  url_for( action: 'select_model' , id: transport_brand ) , remote: true do %>

<%#= collection_select( :model, :id, transport_brand.transportbrands.first.transportmodels, :id, :name ,
  { prompt: "Выберите модель", selected: transport_brand.transportmodels.any? ? transport_brand.transportmodels.first.id.to_s : nil } ,
  onchange: "$(this.form).submit();")  %>

<%# end if transport_brand.transportbrands.any? and transport_brand.transportbrands.first.transportmodels.any? %>

</div>

app/views/transports/_transport_color.erb
<% @colors = Transportcolor.visible %>



<%= form_tag  url_for( action: 'select_color' , id: transport) , remote: true do %>
<table>
  <tr>
    <th>  Цвет ТС </th>
    <td> <%= collection_select( :color, :id, @colors, :id, :name ,
    { prompt: transport.transportcolors.blank? ? "Выберите цвет" : nil,
      selected: transport.transportcolors.any? ? transport.transportcolors.first.id.to_s : nil}) %>
    </td>
    <th>
       <%= submit_tag "Сохранить" %>
    </th>
  </tr>

</table>
<% end %>

app/views/transports/_transportfuellings.erb
<% transportfuellings.each do |tank|  %>
[Объём бака:<%= tank.v_tank %>, мин. остаток:<%= tank.v_tank_min %>]
<% end %>

app/views/transports/_transportloadings.erb
<% transportloadings.each do |loading|  %>
<%= loading.loading %>,
<% end %>

app/views/transports/complete.js.erb
$("#additional").html("<%=j render "additional"%>");
$('#popup_content').html("");
$('#popup').css("display", "none");
$.jGrowl("<%=j flash[:notice]%>");

app/views/transports/index.html.erb
<h2>Транспортные средства</h2>
<%= will_paginate @transports, class: "apple_pagination" %>
<table>
  <tr>
    <th><%= button_to 'Новое ТС', new_transport_path %> </th>
    <td style="width: 130px;">
      <%= link_to params[:showdel] == "true" ? "Скрыть удаленные" : "Показать удаленные", transports_path(showdel: params[:showdel] == "true" ? "false" : "true") %>
    </td>
  </tr>
</table>
<table>
  <tr>
    <th>Рег. номер</th>
    <th>Дата регистрации</th>
    <th>Название</th>
    <th>Описание</th>
    <th>Модель</th>
    <th>VIN номер</th>
    <th>Документ</th>
    <th colspan="4"></th>
  </tr>

<% @transports.each do |transport| %>
  <tr class="<%= cycle("","even") %>">
    <td><%= transport.reg_num %> <span class="red"><%= "удалено" if transport.is_close %></span></td>
    <td><%= transport.created_at.strftime("%d/%m/%Y") %></td>
    <td><%= transport.name %> </td>
    <td><%= transport.description %></td>
    <td><%= transport.transportmodel.name if transport.transportmodel %></td>
    <td><%= transport.vin %></td>
    <td><%= transport.documents.any? ? "Есть" : "Нет" %></td>
    <td class="docs" title="Документы">  <%= link_to image_tag("docs.png"), action: "show_part", id: transport, part: "docs", remote: true %> </td>
    <td class="copy"><%= link_to image_tag("copy.png", title: "Редактировать копию ТС"), edit_transport_path(transport, copy: "true"), data: { confirm: 'Точно?' } %></td>
    <td class="edit"><%= link_to image_tag("edit.png", title: "Редактировать"), edit_transport_path(transport) %></td>
    <td class="del" title="Удалить"><%= link_to image_tag("remove.png", title: "Удалить"), transport, method: :delete, data: { confirm: 'Точно?' } %></td>

  </tr>
<% end %>
</table>
<table>
  <tr> <th colspan="5"><%= button_to 'Новое ТС', new_transport_path if @transports.size > 10%> </th>  </tr>
</table>

<%= will_paginate @transports, class: "apple_pagination" %>

app/views/transports/new.html.erb
<h2>Новое ТС</h2>

<div id="form">
<%= render 'form' %>
</div>

app/views/transports/show.html.erb
<h1>Транспортное средство</h1>

<table border="1">
  <tr>  <th>Название</th>               <td><%= @transport.name %></td></tr>
  <tr>  <th>Описание</th>               <td><%= @transport.description %></td></tr>
  <tr>  <th>Марка и модель</th>         <td><%= render partial: "transport_brand", object: @transport %></td></tr>

  <tr>  <th>Категория ТС</th>           <td><div id="transportcategory"><%= @category %></div></td></tr>
  <tr>  <th>Тип ТС</th>                 <td><div id="transporttype"><%= @type %></div></td></tr>
  <tr>  <th>Вид ТС</th>                 <td><div id="transportkind"><%= @kind %></div></td></tr>

  <tr>  <th>Цвет</th>                   <td><%= render partial: "transport_color", object: @transport %></td></tr>
  <tr>  <th>Год выпуска</th>            <td><%= @transport.year %></td></tr>
  <tr>  <th>VIN номер</th>              <td><%= @transport.vin %></td></tr>
  <tr>  <th>Номер шасси</th>            <td><%= @transport.chassis_num %></td></tr>
  <tr>  <th>Номер кузова</th>           <td><%= @transport.body_num %></td></tr>
  <tr>  <th>Тип двигателя</th>          <td><div id="enginetype"><%= @enginetype %></div></td></tr>
  <tr>  <th>Модель двигателя</th>       <td><div id="select_enginemodel"> <%= render partial: "transport_engine", object: @transport %> </div></td></tr>
  <tr>  <th>Мощность двигателя</th>     <td><div id="power"><%=@enginemodel.power if @enginemodel%> </div></td></tr>
  <tr>  <th>Рабочий объём двигателя</th><td><div id="displacement"><%=@enginemodel.displacement if @enginemodel%></div></td>  </tr>
  <tr>  <th>Наличие погрузки </th>      <td><div id="is_loading"><%= if @transportloadings then "да" else "нет" end  %> </div></td></tr>
  <tr>  <th>Способ погрузки</th>        <td><div id="loading"> <%= render partial: "transportloadings", object: @transportloadings if @transportloadings %></div>
                                        </td></tr>
  <tr>  <th>Наличие топливного бака</th> <td><div id="is_fuelling"><%= if @transportfuellings then "да" else "нет" end  %></div></td></tr>
  <tr>  <th>Топливный бак</th>       <td><div id="tank">
                                            <%= render partial: "transportfuellings", object: @transportfuellings if @transportfuellings %>
                                            </div>
                                        </td></tr>

  <tr>  <th colspan="2"><%= link_to 'Редактировать', edit_transport_path(@transport) %>
    <%= link_to 'Удалить', @transport, method: :delete, data: { confirm: 'Точно?' } %></th>
  </tr>

</table>

<br />

<%= link_to 'Новое ТС', new_transport_path %> | 
<%= link_to 'К транспортным средствам', transports_path %>

app/views/transports/show_part.js.erb
$("#popup_content").html("<%=j render partial: @part, locals: {transport: @transport} %>");
$("#popup_head span").html("ТС: <%=j @transport.reg_num %>");
$("#popup").show(300);