config/routes.rb
Project1::Application.routes.draw do




  resources :contract_relationships

  resources :contracts

  resources :contract_subject_roles

  resources :contract_subject_selects

  resources :contract_subjects


  resources :contract_types


  resources :contractor_representatives


  resources :unv_comments


  resources :truck_drivers


  resources :couplers


  resources :unv_employees


  resources :resourse_types


  resources :unv_types


  resources :employee_histories


  resources :employees
  post "employees/index"

  resources :staff_units


  resources :departments do

  end


  get "unavailables/index"
  get "unavailables/ol"
  get "unavailables/upd"
  get "unavailables/connections"


  resources :duties


  get "wialon/index"

  resources :tables


  resources :columns


  resources :objecttypepropertycolumns


  resources :objecttypeproperties


  resources :objecttypes


  resources :systems


  resources :phoneuses


  resources :phones


  resources :positions


  resources :contractortypes


  resources :contractors


  resources :documents do
       collection do
         get 'show_part'
         post 'select_kind'
         get 'select_kind'
         get 'edit'
       end
  end


  resources :documentkinds


  resources :documenttypes


  resources :functionalgroups do
       collection do
         get 'set_order'
         post 'savesort'
         get 'savesort'
         get 'update_menu'
       end
  end


  resources :people do
     collection do
      get 'phone_person'
     end
  end


  resources :transportexploitations


  resources :transporttanks


  resources :transportloadings


  resources :transportecologicals


  resources :enginemodels


  resources :enginetypes


  resources :transportkinds


  resources :transportcolors


  resources :transporttypes


  resources :transports



  get "sms/index"

  resources :testguids, as: 'tst'




  devise_for :admins







  get "main/index"









   root :to => 'main#index'
   match '/' => 'main#index'
   
   

devise_for :users, :skip => [:sessions]
as :user do
  get 'signin' => 'devise/sessions#new', :as => :new_user_session
  post 'signin' => 'devise/sessions#create', :as => :user_session
  delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
end

scope "/admin" do
  resources :users, :usergroups, :roles, :functionals
end

scope "/transport" do
  resources :transportbrands
  resources :transportmodels
  resources  :transportcategories
end


match ':controller(/:action(/:id))(.:format)'
  
end

app/models/enginemodel.rb
# -*- encoding : utf-8 -*-
class Enginemodel < ActiveRecord::Base
  attr_accessible :displacement, :enginetype_id, :name, :power, :power_kvt, :is_close

 

  validates :name, :displacement, :power, :power_kvt, :enginetype_id,  presence: true
  validates  :displacement, :power, :power_kvt,  numericality: true

  has_and_belongs_to_many :transports
  belongs_to :enginetype
  audited

  scope :visible, where("is_close != ?", true)

  def close
    self.update_attribute( :is_close, true )
  end

  def unclose
    self.update_attribute( :is_close, false )
  end

  
  
end

app/controllers/enginemodels_controller.rb
# -*- encoding : utf-8 -*-
class EnginemodelsController < ApplicationController


  def index
    if params[:type]
      @enginetype = Enginetype.find(params[:type])
      @enginemodels = @enginetype.enginemodels.paginate(page: params[:page], per_page: 20)
    else
      @enginemodels = Enginemodel.order(:enginetype_id).paginate(page: params[:page], per_page: 20)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @enginemodels }
    end
  end



  def show
    @enginemodel = Enginemodel.find(params[:id])
    @enginetype = @enginemodel.enginetype
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @enginemodel }
    end
  end


  def new
    @enginetype = Enginetype.find(params[:type]) if params[:type]
    @enginemodel = Enginemodel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @enginemodel }
    end
  end


  def edit
    @enginemodel = Enginemodel.find(params[:id])
    @enginetype = @enginemodel.enginetype
  end


  def create
    params[:enginemodel].delete(:enginetype_id) if params[:enginemodel][:enginetype_id] == ''
    @enginemodel = Enginemodel.new(params[:enginemodel])
    @enginetype = @enginemodel.enginetype

    respond_to do |format|
      if @enginemodel.save
        format.html { redirect_to enginemodels_url( type: @enginemodel.enginetype_id ), notice: 'Модель двигателя ТС добавлена' }
        format.json { render json: @enginemodel, status: :created, location: @enginemodel }
      else

        format.html { render action: "new" }
        format.json { render json: @enginemodel.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @enginemodel = Enginemodel.find(params[:id])
    @enginetype = @enginemodel.enginetype
    respond_to do |format|
      if @enginemodel.update_attributes(params[:enginemodel])
        format.html { redirect_to @enginemodel, notice: 'Модель двигателя ТС сохранена' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @enginemodel.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @enginemodel = Enginemodel.find(params[:id])
    enginetype = @enginemodel.enginetype_id
    @enginemodel.close

    respond_to do |format|
      format.html { redirect_to enginemodels_url( type: enginetype) }
      format.json { head :no_content }
    end
  end
end

app/helpers/enginemodels_helper.rb
# -*- encoding : utf-8 -*-
module EnginemodelsHelper
end

app/views/enginemodels/_form.html.erb
  <% if @enginemodel.errors.any? %>
    <div id="error_explanation">
      <h2> Ошибок: <%= @enginemodel.errors.count %></h2>
           <ul>
      <% @enginemodel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for(@enginemodel) do |f| %>

<table>
  <tr>
       <th><%= f.label :enginetype_id , "Тип двигателя ТС" %> </th>
       <td><%= f.collection_select( :enginetype_id, Enginetype.visible, :id, :name,
              { prompt: @enginemodel.enginetype ? nil : "Выберите тип двигателя ТС",
              selected: @enginemodel.enginetype ? @enginemodel.enginetype.id : nil}  )%>
       </td>
  </tr>
  <tr> <th><%= f.label :name, "Модель двигателя ТС" %> </th> <td><%= f.text_field :name %> </td> </tr>
  <tr> <th><%= f.label :power, "Мощность двигателя л.с" %> </th> <td> <%= f.number_field :power %> </td> </tr>
  <tr> <th><%= f.label :power_kvt, "Мощность двигателя кВт" %> </th> <td> <%= f.number_field :power_kvt %> </td> </tr>
  <tr> <th> <%= f.label :displacement, 'Рабочий объём двигателя' %> </th> <td><%= f.number_field :displacement %> </td> </tr>
  <tr> <th> <%= f.label :is_close, 'Удалено' %> </th> <td><%= f.check_box :is_close %> </td> </tr>
  <tr> <th colspan="2"> <%= f.submit "Сохранить" %>
                        <%= link_to 'Вернуться к моделям двигателя ТС', enginemodels_path( type: @enginetype ? @enginetype.id : nil ) %>
       </th>
  </tr>

</table>
<% end %>

app/views/enginemodels/edit.html.erb
<h2>Тип двигателя: <%=link_to @enginetype.name, enginetypes_path %>. <br/> Редактирование модели: <%= @enginemodel.name %></h2>

<%= render 'form' %>

app/views/enginemodels/index.html.erb
<h2><%=link_to "Тип двигателя: #{@enginetype.name}", enginetypes_path if @enginetype%> <br/>Модели двигателей ТС</h2>
<%= will_paginate @enginemodels, class: "apple_pagination" %>
<table>
  <tr>
    <th>Тип двигателя ТС</th>
    <th>Модель двигателя ТС</th>
    <th>Мощность двигателя</th>
    <th>Рабочий объём двигателя</th>
    <th colspan="2"></th>

  </tr>

<% @enginemodels.each do |enginemodel| %>
  <tr class="<%= cycle("","even") %>">
    <td><%= enginemodel.enginetype.name if enginemodel.enginetype%> </td>
    <td><%= enginemodel.name %> <span class="red"><%= "удалено" if enginemodel.is_close  %></span></td>
    <td><%= enginemodel.power %></td>
    <td><%= enginemodel.displacement %></td>
    <td class="edit"><%= link_to link_to image_tag("edit.png", style: "width: 20px;"), edit_enginemodel_path(enginemodel) %></td>
    <td class="del" title="Удалить"><%= link_to link_to image_tag("remove.png", style: "width: 20px;"), enginemodel, method: :delete, data: { confirm: 'Точно?' } %></td>
  </tr>
<% end %>
  <tr> <th> <%= button_to 'Новая модель двигателя ТС', new_enginemodel_path( type: @enginetype ? @enginetype.id : nil) %> </th>
       <th colspan="5"> <%= link_to 'Все модели двигателя ТС', enginemodels_path if @enginetype%>
                        <%= link_to 'Вернуться к типам двигателя ТС', enginetypes_path %> </th> </tr>
</table>

<%= will_paginate @enginemodels, class: "apple_pagination" %>

app/views/enginemodels/new.html.erb
<h2> <%=link_to "Тип двигателя: #{@enginetype.name}", enginetypes_path if @enginetype %> <br/> Добавление модели двигателя ТС.</h2>

<%= render 'form' %>

app/views/enginemodels/show.html.erb
<h1>Тип двигателя: <%= @enginetype.name %>. Модель: <%= @enginemodel.name %></h1>

<table>
  <tr> <th style="width: 200px;">Модель двигателя ТС: </th> <td> <%= @enginemodel.name %> </td> </tr>
  <tr> <th>Мощность двигателя: </th> <td>   <%= @enginemodel.power %></td> </tr>
  <tr> <th>Рабочий объем двигателя: </th> <td>  <%= @enginemodel.displacement %> </td> </tr>
  <tr> <th>Удалено: </th> <td>  <%= @enginemodel.is_close %> </td> </tr>

  <tr> <th colspan="2"><%= link_to 'Редактировать', edit_enginemodel_path(@enginemodel) %> 
<%= link_to 'Вернуться', enginemodels_path( type: @enginetype.id ) %> </th> </tr>

</table>