config/routes.rb
Project1::Application.routes.draw do




  resources :contract_relationships

  resources :contracts

  resources :contract_subject_roles

  resources :contract_subject_selects

  resources :contract_subjects


  resources :contract_types


  resources :contractor_representatives


  resources :unv_comments


  resources :truck_drivers


  resources :couplers


  resources :unv_employees


  resources :resourse_types


  resources :unv_types


  resources :employee_histories


  resources :employees
  post "employees/index"

  resources :staff_units


  resources :departments do

  end


  get "unavailables/index"
  get "unavailables/ol"
  get "unavailables/upd"
  get "unavailables/connections"


  resources :duties


  get "wialon/index"

  resources :tables


  resources :columns


  resources :objecttypepropertycolumns


  resources :objecttypeproperties


  resources :objecttypes


  resources :systems


  resources :phoneuses


  resources :phones


  resources :positions


  resources :contractortypes


  resources :contractors


  resources :documents do
       collection do
         get 'show_part'
         post 'select_kind'
         get 'select_kind'
         get 'edit'
       end
  end


  resources :documentkinds


  resources :documenttypes


  resources :functionalgroups do
       collection do
         get 'set_order'
         post 'savesort'
         get 'savesort'
         get 'update_menu'
       end
  end


  resources :people do
     collection do
      get 'phone_person'
     end
  end


  resources :transportexploitations


  resources :transporttanks


  resources :transportloadings


  resources :transportecologicals


  resources :enginemodels


  resources :enginetypes


  resources :transportkinds


  resources :transportcolors


  resources :transporttypes


  resources :transports



  get "sms/index"

  resources :testguids, as: 'tst'




  devise_for :admins







  get "main/index"









   root :to => 'main#index'
   match '/' => 'main#index'
   
   

devise_for :users, :skip => [:sessions]
as :user do
  get 'signin' => 'devise/sessions#new', :as => :new_user_session
  post 'signin' => 'devise/sessions#create', :as => :user_session
  delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
end

scope "/admin" do
  resources :users, :usergroups, :roles, :functionals
end

scope "/transport" do
  resources :transportbrands
  resources :transportmodels
  resources  :transportcategories
end


match ':controller(/:action(/:id))(.:format)'
  
end

app/models/functional.rb
# -*- encoding : utf-8 -*-
class Functional < ActiveRecord::Base
  self.primary_key = :id
  attr_accessible :description, :end, :name, :part, :start, :is_close

  has_and_belongs_to_many :users
  has_and_belongs_to_many :usergroups
  has_and_belongs_to_many :roles
  audited

  #validates :id, presence: true
  before_validation :ensure_uuid

  scope :visible, where("is_close != ?", true)

  def close
    self.update_attribute( :is_close, true )
  end

  def unclose
    self.update_attribute( :is_close, false )
  end


  def ensure_uuid; self.id ||= SecureRandom.uuid end
end

app/controllers/functionals_controller.rb
# -*- encoding : utf-8 -*-
class FunctionalsController < ApplicationController
  before_filter :authenticate_user!
  # GET /functionals
  # GET /functionals.json
  def index
   if params[:group]
      @group = Usergroup.find(params[:group])
      @functionals = @group.functionals
      @msg = "Группа #{@group.name}"
    elsif params[:role]
      @role = Role.find(params[:role])
      @functionals = @role.functionals
      @msg = "Роль #{@role.name}"
    elsif params[:user]
      @user = User.find(params[:user])
      @functionals = @user.functionals
      @msg = "Пользователь #{@user.email}"
    else
      @functionals = Functional.all
    end


    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @functionals }
    end
  end

  # GET /functionals/1
  # GET /functionals/1.json
  def show
    @functional = Functional.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @functional }
    end
  end

  # GET /functionals/new
  # GET /functionals/new.json
  def new
    @functional = Functional.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @functional }
    end
  end

  # GET /functionals/1/edit
  def edit
    @functional = Functional.find(params[:id])
  end

  # POST /functionals
  # POST /functionals.json
  def create
    @functional = Functional.new(params[:functional])

    respond_to do |format|
      if @functional.save
        format.html { redirect_to @functional, notice: 'Functional was successfully created.' }
        format.json { render json: @functional, status: :created, location: @functional }
      else
        format.html { render action: "new" }
        format.json { render json: @functional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /functionals/1
  # PUT /functionals/1.json
  def update
    @functional = Functional.find(params[:id])

    respond_to do |format|
      if @functional.update_attributes(params[:functional])
        format.html { redirect_to @functional, notice: 'Функционал сохранен' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @functional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /functionals/1
  # DELETE /functionals/1.json
  def destroy
    @functional = Functional.find(params[:id])
    @functional.close
    respond_to do |format|
      format.html { redirect_to functionals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/functionals_helper.rb
# -*- encoding : utf-8 -*-
module FunctionalsHelper
end

app/views/functionals/_form.html.erb
  <% if @functional.errors.any? %>
    <div id="error_explanation">
      <h2>Ошибок: <%= @functional.errors.count %></h2>

      <ul>
      <% @functional.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for(@functional) do |f| %>

<table>
  <tr><th><%= f.label "Наименование" %></th><td><%= f.text_field :name %></td></tr>
  <tr><th><%= f.label "Описание" %></th><td><%= f.text_area :description %></td></tr>
  <tr><th><%= f.label "Модуль" %></th><td><%= f.text_field :part %></td></tr>
  <tr><th><%= f.label "Начало действия" %></th><td><%= f.date_select :start %></td></tr>
  <tr><th><%= f.label "Окончание действия" %></th><td><%= f.date_select :end %></td></tr>
  <tr><th><%= f.label :is_close, "Удален" %></th><td><%= f.check_box :is_close %></td></tr>
  <tr><th colspan="2"> <%= f.submit "Сохранить" %> <%= link_to 'Вернуться', functionals_path %></th></tr>

</table>
<% end %>

app/views/functionals/edit.html.erb
<h2>Редактирование функционала</h2>

<%= render 'form' %>

app/views/functionals/index.html.erb
<h2>Функционал. <%= @msg if @msg %></h2>
<%= link_to "Все функционалы", usergroups_path  if @msg %>

<table>
  <tr>
    <th>Наименование</th>
    <th><%= link_to 'Роли', roles_path %></th>
    <th><%= link_to 'Группы', usergroups_path %></th>
    <th><%= link_to "Пользователи" , users_path %> </th>
    <th colspan="3"></th>
  </tr>

<% @functionals.each do |functional| %>
  <tr class="<%= cycle("","even") %>">
    <td><%= functional.name %> <span class="red"><%= "удалено" if functional.is_close  %></span></td>
    <td><%= link_to "Роли с функционалом" ,roles_path(functional: functional) if functional.roles.any? %> </td>
    <td><%= link_to "Группы с функционалом" ,usergroups_path(functional: functional) if functional.usergroups.any? %> </td>
    <td><%= link_to "Пользователи с функционалом" ,users_path(functional: functional) if functional.users.any? %> </td>
    <td><%= link_to 'Просмотр' , functional %> </td>
    <td class="edit"><%= link_to link_to image_tag("edit.png", style: "width: 20px;"), edit_functional_path(functional) %></td>
    <td class="del" title="Удалить"><%= link_to link_to image_tag("remove.png", style: "width: 20px;"), functional, method: :delete, data: { confirm: 'Точно?' } %></td>
  </tr>

<% end %>
  <tr><th colspan="7"><%= link_to 'Новый функционал', new_functional_path %></th> </tr>
</table>

app/views/functionals/new.html.erb
<h2>Новый функционал</h2>

<%= render 'form' %>

app/views/functionals/show.html.erb
<h2>Просмотр </h2>
<table>
  <tr><th>Название:</th><td><%= @functional.name %></td></tr>
  <tr><th>Описание:</th><td><%= @functional.description %></td></tr>
  <tr><th>Модуль:</th><td><%= @functional.part %></td></tr>
  <tr><th>Начало действия:</th><td><%= @functional.start %></td></tr>
  <tr><th>Окончание действия:</th><td><%= @functional.end %></td></tr>
  <tr><th colspan="2"><%= link_to 'Редактировать', edit_functional_path(@functional) %> <%= link_to 'Вернуться', functionals_path %></th></tr>
</table>