config/routes.rb
Project1::Application.routes.draw do




  resources :contract_relationships

  resources :contracts

  resources :contract_subject_roles

  resources :contract_subject_selects

  resources :contract_subjects


  resources :contract_types


  resources :contractor_representatives


  resources :unv_comments


  resources :truck_drivers


  resources :couplers


  resources :unv_employees


  resources :resourse_types


  resources :unv_types


  resources :employee_histories


  resources :employees
  post "employees/index"

  resources :staff_units


  resources :departments do

  end


  get "unavailables/index"
  get "unavailables/ol"
  get "unavailables/upd"
  get "unavailables/connections"


  resources :duties


  get "wialon/index"

  resources :tables


  resources :columns


  resources :objecttypepropertycolumns


  resources :objecttypeproperties


  resources :objecttypes


  resources :systems


  resources :phoneuses


  resources :phones


  resources :positions


  resources :contractortypes


  resources :contractors


  resources :documents do
       collection do
         get 'show_part'
         post 'select_kind'
         get 'select_kind'
         get 'edit'
       end
  end


  resources :documentkinds


  resources :documenttypes


  resources :functionalgroups do
       collection do
         get 'set_order'
         post 'savesort'
         get 'savesort'
         get 'update_menu'
       end
  end


  resources :people do
     collection do
      get 'phone_person'
     end
  end


  resources :transportexploitations


  resources :transporttanks


  resources :transportloadings


  resources :transportecologicals


  resources :enginemodels


  resources :enginetypes


  resources :transportkinds


  resources :transportcolors


  resources :transporttypes


  resources :transports



  get "sms/index"

  resources :testguids, as: 'tst'




  devise_for :admins







  get "main/index"









   root :to => 'main#index'
   match '/' => 'main#index'
   
   

devise_for :users, :skip => [:sessions]
as :user do
  get 'signin' => 'devise/sessions#new', :as => :new_user_session
  post 'signin' => 'devise/sessions#create', :as => :user_session
  delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
end

scope "/admin" do
  resources :users, :usergroups, :roles, :functionals
end

scope "/transport" do
  resources :transportbrands
  resources :transportmodels
  resources  :transportcategories
end


match ':controller(/:action(/:id))(.:format)'
  
end

app/controllers/contractortypes_controller.rb
# -*- encoding : utf-8 -*-
class ContractortypesController < ApplicationController


  def index
    @contractortypes = Contractortype.paginate(page: params[:page], per_page: 30)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contractortypes }
    end
  end



  def new
    @contractortype = Contractortype.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contractortype }
    end
  end


  def edit
    @contractortype = Contractortype.find(params[:id])
  end


  def create
    @contractortype = Contractortype.new(params[:contractortype])
    @contractortype.id ||= SecureRandom.uuid
    respond_to do |format|
      if @contractortype.save
        format.html { redirect_to edit_contractortype_url(@contractortype), notice: 'Contractortype добавлен.' }
        format.json { render json: @contractortype, status: :created, location: @contractortype }
      else
        format.html { render action: "new" }
        format.json { render json: @contractortype.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @contractortype = Contractortype.find(params[:id])

    respond_to do |format|
      if @contractortype.update_attributes(params[:contractortype])
        format.html { redirect_to edit_contractortype_url(@contractortype), notice: 'Contractortype сохранен.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contractortype.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @contractortype = Contractortype.find(params[:id])
    @contractortype.close

    respond_to do |format|
      format.html { redirect_to contractortypes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contractortypes_helper.rb
# -*- encoding : utf-8 -*-
module ContractortypesHelper
end

app/views/contractortypes/_form.html.erb
<% if @contractortype.errors.any? %>
    <div id="error_explanation">
      <h2>Ошибок: <%= @contractortype.errors.count %></h2>

      <ul>
      <% @contractortype.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for(@contractortype) do |f| %>
  <table>
    <tr>
      <th><%= f.label :name, "Наименование" %></th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th><%= f.label :descr, "Описание" %></th>
      <td><%= f.text_area :descr %></td>
    </tr>
    <tr>
      <th colspan="2"><%= f.submit "Сохранить" %> <%= link_to 'Вернуться', contractortypes_path %></th>
    </tr>
  </table>
<% end %>

app/views/contractortypes/edit.html.erb
<h2>Редактирование типа контрагента</h2>
<div id="form">
<%= render 'form' %>
</div>

app/views/contractortypes/index.html.erb
<h2>Типы контрагентов</h2>
<%= will_paginate @contractortypes, class: "apple_pagination" %>
<table>
  <tr>
    <th>Наименование</th>
    <th>Описание</th>
    <th colspan="2"></th>

  </tr>

<% @contractortypes.each do |contractortype| %>
  <tr>
    <td><%= contractortype.name %></td>
    <td><%=link_to "Создать контрагента", new_contractor_path(contractortype:contractortype ) %></td>
    <td><%= contractortype.descr %></td>
    <td class="edit">
      <%= link_to image_tag("edit.png"), edit_contractortype_path(contractortype) %>
    </td>
    <td class="del" title="Удалить">
      <%= link_to image_tag("remove.png"), contractortype, method: :delete, data: { confirm: 'Точно?' } %>
    </td>
  </tr>
<% end %>
<tr><th><%= link_to 'Новый тип контрагента', new_contractortype_path %></th></tr>

</table>

<%= will_paginate @contractortypes, class: "apple_pagination" %>

app/views/contractortypes/new.html.erb
<h2>Новый тип контрагента</h2>
<div id="form">
<%= render 'form' %>
</div>